package emils
Object a = new Object()
Object b = new Object()

a + b    		//a.plus(b)
a - b    		//a.minus(b)
a * b    		//a.multiply(b)
a ** b    		//a.power(b)
a / b    		//a.div(b)
a % b    		//a.mod(b)
a | b    		//a.or(b)
a & b    		//a.and(b)
a ^ b    		//a.xor(b)
a++ 			//a.next()
++a		 		//a.next()
a-- 	 		//a.previous()
--a 			//a.previous()
